### ISSUE TITLE
Unable to run abritamr in batch mode , giving error parallel: invalid option -- '-'

### ISSUE THREAD

**Issue by ranjanmanishblue** [MDU-PHL/abritamr#23]
Hi,
I am unable to run abritamr in batch mode as following error occurs. The screenshot is attached here. I followed the instruction as given on github page. I tried every possibilities present on internet, that does not worked so far. If you have better suggestions , please let me know?  With single input file abritamr is running fine.
Thanking you!
Manish Ranjan
![Screenshot from 2023-01-25 12-56-16](https://user-images.githubusercontent.com/40167764/214505846-da48d477-4d7a-450b-8fbf-8e4c74bf7b09.png)

**Comment by bbalog87** [comment]
Hi,
I have exactly the same error.

**Comment by kristyhoran** [comment]
Under investigation

**Comment by KatyaArnold** [comment]
hi, I have the same error - also when running on the single file:
![Capture](https://github.com/MDU-PHL/abritamr/assets/62796377/c0d246a4-2dc0-47c1-b487-d32090d0700e)
Would be gratefull to your help!
