### ISSUE TITLE
Difficulty in running the abritamr report

### ISSUE THREAD

**Issue by vmevada102** [MDU-PHL/abritamr#26]
After completion of run, i would like to generate the report as availability of functionality.

Unfortunately, i am receiving following error for QC file.

(abritamr) user@bioscience:/data/mg/abritamr$ abritamr report -m summary_matches.txt -p summary_partials.txt
[INFO:03/06/2023 10:16:02 AM] You are generating a general report
[INFO:03/06/2023 10:16:02 AM] Now checking all input files are present.
[INFO:03/06/2023 10:16:02 AM] Checking that QC is present.
[CRITICAL:03/06/2023 10:16:02 AM] The QC file supplied () does not exist. Please check your inputs and try again.

Kindly guide me to generate QC file

**Comment by LiZhihua1982** [comment]
Hi 
    I also want to know how to generate QC file? 

Li Zhihua

**Comment by LiZhihua1982** [comment]
(abritamr) lizhihua@lizhihua-T640:/media/lizhihua/data/30type/spades_out/HL1$ abritamr report --qc abritamr_qc_template.csv --matches abritamr/summary_matches.txt -p abritamr/summary_partials.txt 
[INFO:04/28/2023 09:29:06 AM] You are generating a general report
[INFO:04/28/2023 09:29:06 AM] Now checking all input files are present.
[INFO:04/28/2023 09:29:06 AM] Checking that QC is present.
[INFO:04/28/2023 09:29:06 AM] Checking if file abritamr_qc_template.csv exists
[INFO:04/28/2023 09:29:06 AM] abritamr_qc_template.csv is present.
[INFO:04/28/2023 09:29:06 AM] Checking that summary_matches is present.
[INFO:04/28/2023 09:29:06 AM] Checking if file abritamr/summary_matches.txt exists
[INFO:04/28/2023 09:29:06 AM] abritamr/summary_matches.txt is present.
[INFO:04/28/2023 09:29:06 AM] Checking that summary_partials is present.
[INFO:04/28/2023 09:29:06 AM] Checking if file abritamr/summary_partials.txt exists
[INFO:04/28/2023 09:29:06 AM] abritamr/summary_partials.txt is present.
[INFO:04/28/2023 09:29:06 AM] Applying MDU business logic matches.
[INFO:04/28/2023 09:29:06 AM] Checking the format of the QC file
[CRITICAL:04/28/2023 09:29:06 AM] There seems to be a problem with your QC file. This file must have ISOLATE,SPECIES_EXP,SPECIES_OBS,TEST_QC. Please check your input and try again.
I feel difficult to prepare the abritamr_qc_template.csv, would you add a test template?

**Comment by butterbee** [comment]
Has anyone successful in performing abritamr report command? 
I managed to execute the command without an error however all the run_ID.xlsx created at the end were empty. 
How this can be possible? Is there a special way to produce a QC file?
