### ISSUE TITLE
parallel: not found

### ISSUE THREAD

**Issue by MHassanSaeed** [MDU-PHL/abritamr#29]
Hi 

I am getting the following error:
`[CRITICAL:05/17/2023 12:59:31 PM] Your amrfinder database version is NOT 2022-08-09.1. abriTAMR will still run but behaviour may not be as expected in terms of binnig genes into the appropriate drug classes.
[INFO:05/17/2023 12:59:31 PM] You are running abritamr in batch mode. Now executing : parallel -j 16 --colsep '\t' 'mkdir -p {1} && amrfinder -n {2} -o {1}/amrfinder.out --plus --organism Enterococcus_faecalis --threads 1 -d AMRFINDER_DB' :::: nett.txt
[CRITICAL:05/17/2023 12:59:31 PM] There appears to have been a problem with running amrfinder plus. The following erro has been reported :
 /bin/sh: 1: parallel: not found

[CRITICAL:05/17/2023 12:59:31 PM] The amrfinder output : LH_NE_10.fna/amrfinder.out is missing. Something has gone wrong with AMRfinder plus. Please check all inputs and try again.`

Please help me out to resolve the error.

Second, does the database work on all Enterococcus species? and
how can I update the database?

Thanks,
Hassan

**Comment by Heraud04** [comment]
need install parallel
Try:
conda install -c conda-forge parallel

**Comment by bernt-matthias** [comment]
fixed at bioconda https://github.com/bioconda/bioconda-recipes/pull/41088
