### ISSUE TITLE
Issue with snakemake pipeline?

### ISSUE THREAD

**Issue by jhawkey** [MDU-PHL/abritamr#7]
Hi,

I'm having some issues trying to run this pipeline. I've installed via conda on a nectar instance, and when I call abritamr I get the following output:

```
(abritamr) ubuntu@nectar2:/mnt/nectar/analyses/mdu_amr_pipeline_test$ abritamr -c contig_file.txt
[INFO:07/17/2021 03:16:37 AM] Checking the structure of your input file.
[INFO:07/17/2021 03:16:37 AM] The input file seems to be in the correct format. Thank you.
[INFO:07/17/2021 03:16:37 AM] Checking that the input data is present. If present will link to /mnt/nectar/analyses/mdu_amr_pipeline_test
[INFO:07/17/2021 03:16:37 AM] Checking if file /mnt/nectar/analyses/klebs_oxy/polishing/Kox100_round3.fasta exists
[INFO:07/17/2021 03:16:37 AM] Setting up workflow files.
[INFO:07/17/2021 03:16:37 AM] Writing config file
[INFO:07/17/2021 03:16:37 AM] Writing snakefile
[INFO:07/17/2021 03:16:37 AM] Written Snakefile and config.yaml to /mnt/nectar/analyses/mdu_amr_pipeline_test
[INFO:07/17/2021 03:16:37 AM] Running pipeline using command snakemake -s Snakefile_abritamr -j 16  2>&1 | tee -a job.log. This may take some time.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/abritamr/bin/abritamr", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/abritamr/lib/python3.6/site-packages/abritamr/abritamr.py", line 112, in main
    args.func(args)
  File "/home/ubuntu/miniconda3/envs/abritamr/lib/python3.6/site-packages/abritamr/abritamr.py", line 18, in run_pipeline
    return P.run_amr()
  File "/home/ubuntu/miniconda3/envs/abritamr/lib/python3.6/site-packages/abritamr/AmrSetup.py", line 219, in run_amr
    wkflow = self.run_snakemake()
  File "/home/ubuntu/miniconda3/envs/abritamr/lib/python3.6/site-packages/abritamr/AmrSetup.py", line 191, in run_snakemake
    wkfl = subprocess.run(cmd, shell=True, capture_output=True)
  File "/home/ubuntu/miniconda3/envs/abritamr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

AMRFinder Plus is installed, and I am able to run it successfully on the genome that I've used in the above test.

**Comment by andersgs** [comment]
It seems Conda installed an older version of Python. The capture_output option was only introduced in Python 3.7. Will need to fix the minimum Python version. 

Can you upgrade Python and try again? Thank you @jhawkey

**Comment by andersgs** [comment]
Can you send me the command you used to install? The setup.py does restrict to Python 3.7 and above. So, I am not clear how it installed on an older version of Python.

**Comment by jhawkey** [comment]
Thanks @andersgs!  My initial install was using the conda command listed in the readme. I attempted to get that environment to upgrade to Python3.7 but had too many conflicts. So instead I created my own conda environment manually, ensuring I had  Python3.7 (following the PyPi instructions, but needed to add parallel to get it to work):

```
conda create -n abritamr2 -c bioconda python=3.7
conda activate abritamr2
conda install ncbi-amrfinderplus
amrfinder -U
pip3 install abritamr
conda install parallel
```

This new environment `abritamr2` works well on my test sample. However I did notice that this new environment has a different command to the one that I posted above - I needed to use `abritamr run` as listed on the README, whether in the environment created using `conda create -n <name> -c bioconda abritamr` the command was simply `abritamr` and the options were slightly different. So perhaps the conda environment is pulling an older version of the pipeline?

**Comment by andersgs** [comment]
Sometimes conda doesn’t install the latest recipe. Can you confirm you get the same behaviour if you run `conda install -c conda-forge -c bioconda -c default abritamr= 1.0.0` or `conda create -n abritamr -c conda-forge -c bioconda abritamr=1.0.0`?

**Comment by jhawkey** [comment]
I can confirm that when creating a new environment and specifying `-c conda-forge -c bioconda -c default abritamr=1.0.0`, conda installs the latest version of the pipeline (so requires `abritamr run`, rather than the plain `abritamr` command).

**Comment by andersgs** [comment]
I have updated the suggested command to run to install in order to explicit about the version. Otherwise, it is possible older versions get installed. 

@jhawkey please feel free to reopen if you have related issues. Thank you.
