### ISSUE TITLE
correct installation instructions

### ISSUE THREAD

**Issue by Koen-vdl** [MDU-PHL/abritamr#8]
Please correct : `conda create -n abritamr -c bioconda ncbi-amrfinder` to `conda create -n abritamr -c bioconda ncbi-amrfinderplus`

**Comment by jdeligt** [comment]
might even need conda install -y -c bioconda -c conda-forge ncbi-amrfinderplus
my pull request ened up in me getting V.3.10.1 rather than 3.10.1
